name: Frontend_Workshop_Demo

on:
  push:
    branches:
        - 'feature/**'
        - 'bugfix/**'
        - 'chore/**'
        - 'hotfix/**'
        - main
        - master
env:
    SERVER_IP: 'xxx-x-x-x'
    COMPANY_NAME: 'IOIP'
    REPO_NAME: ${{github.repository}}
    EVENT_NAME: ${{github.event_name}}


jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v5
        - uses: actions/setup-node@v6
          with:
            node-version: '24.x'
            cache: 'npm'
        - run: node -v

